id: configuration-actions
version: {{ .Version }}
description: |
{{ .Description | Indent 2 }}
actions:
{{- $hasPre := false }}
{{- $hasPost := false }}
{{- range .PrePostActions }}
  {{- if eq .Action "Pre" }}{{ $hasPre = true }}{{ end }}
  {{- if eq .Action "Post" }}{{ $hasPost = true }}{{ end }}
{{- end }}
{{- if $hasPre }}
  - id: pre-actions
    description:
    steps:
    {{- range .PrePostActions }}
      {{- if eq .Action "Pre" }}
      - id: {{ ReplaceAll .RelativePath "_" "-" | ToLower }}
        description: {{ .StepDescription }}
        processor: {{ .Processor }}
        config:
          filename: {{ .RelativePath }}
          {{- if ne .SourceSystem "" }}
          source-system: {{ .SourceSystem }}
          {{- end }}
        type: execute
        {{- end }}
    {{- end }}
{{- end }}
{{- if $hasPost }}
  - id: post-actions
    description:
    steps:
    {{- range .PrePostActions }}
      {{- if eq .Action "Post" }}
      - id: {{ ReplaceAll .RelativePath "_" "-" | ToLower }}
        description: {{ .StepDescription }}
        processor: {{ .Processor }}
        config:
          filename: {{ .RelativePath }}
          {{- if ne .SourceSystem "" }}
          source-system: {{ .SourceSystem }}
          {{- end }}
        type: execute
        {{- end }}
    {{- end }}
{{- end }}
