INSERT INTO dict_generic 
(dict_name,source_description,source_value,target_value,target_attribute) VALUES
	 ('cable_type','','TYPE_AUTONOMOUS','N/A',''),
	 ('cable_type','','TYPE_CROSS_CONNECTION','',''),
	 ('cable_type','','TYPE_DARK_FIBER','',''),
	 ('cable_type','','TYPE_IP_TRANSIT','',''),
	 ('cable_type','','TYPE_JUMPER','',''),
	 ('cable_type','','TYPE_PEERING_EX','N/A',''),
	 ('cable_type','','TYPE_RADIO','N/A',''),
	 ('cable_type','','TYPE_TRANSPORT','',''),
	 ('cable_type','','TYPE_UNKNOWN','N/A',''),
	 ('ip_status','ACTIVE','ACTIVE','Assigned','ip-subnet.status'),
	 ('ip_status','active','active','Assigned','ip-subnet.status'),
	 ('ip_status','RELEASED','RELEASED','Aging','ip-subnet.status'),
	 ('ip_status','released','released','Aging','ip-subnet.status'),
	 ('ip_status','RESERVED','RESERVED','Reserved','ip-subnet.status'),
	 ('ip_status','reserved','reserved','Reserved','ip-subnet.status'),
	 ('ip_type','Private','LAN','Private','address-space.type'),
	 ('ip_type','Public','WAN','Public','address-space.type'),
	 ('link_type','','TYPE_AUTONOMOUS','',''),
	 ('link_type','TYPEr Cabinets','TYPE_CROSS_CONNECTION','',''),
	 ('link_type','TYPEr Cabinets','TYPE_DARK_FIBER','',''),
	 ('link_type','TYPEr Cabinets','TYPE_IP_TRANSIT','',''),
	 ('link_type','','TYPE_JUMPER','',''),
	 ('link_type','TYPEr Cabinets','TYPE_PEERING_EX','',''),
	 ('link_type','','TYPE_RADIO','',''),
	 ('link_type','','TYPE_TRANSPORT','',''),
	 ('link_type','','TYPE_UNKNOWN','N/A','');
