name: Sanity Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Sanity Tests
      run: npx playwright test -g "@sanity"

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/

    - name: Send Email
      run: node sendReport.js
      env:
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}